## Scaling 변환
- (실제값 - 예측값)

In [7]:
from sklearn.preprocessing import StandardScaler
import sklearn
import numpy as np

import pandas as pd

train = pd.read_csv('train.csv')
train.head()

   id     Sex  Age  Height  Weight  Duration  Heart_Rate  Body_Temp  Calories
0   0    male   36   189.0    82.0      26.0       101.0       41.0     150.0
1   1  female   64   163.0    60.0       8.0        85.0       39.7      34.0
2   2  female   51   161.0    64.0       7.0        84.0       39.8      29.0
3   3    male   20   192.0    90.0      25.0       105.0       40.7     140.0
4   4  female   38   166.0    61.0      25.0       102.0       40.6     146.0

In [10]:
y = np.log1p(train['Calories'])
scaler = StandardScaler()



numeric_features = ['Age', 'Height', 'Weight', 'Duration', 'Heart_Rate', 'Body_Temp']
train[numeric_features].head(1)

   Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0   36   189.0    82.0      26.0       101.0       41.0

In [15]:
X = train[numeric_features]
X_scaled = scaler.fit_transform(X)
X_scaled[0]

array([-0.3571921 ,  1.11523482,  0.49020109,  1.2663241 ,  0.58371421,
        1.23577241])

In [21]:
X.head(1)

   Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0   36   189.0    82.0      26.0       101.0       41.0

In [18]:
X_combined = pd.concat([
    pd.DataFrame(X_scaled, columns = numeric_features),
    train[['Sex_female','Sex_male']]
], axis = 1)

X_combined.head()

KeyError: "None of [Index(['Sex_female', 'Sex_male'], dtype='object')] are in the [columns]"

In [22]:
X_combined.head()

NameError: name 'X_combined' is not defined

# 학습/검증 데이터 분할
- 기본 원칙 : 층화추출 (비율에 따라 데이터셋 분리)
- 아래 코드는 층화추출이 된 상태가 아님 -> 무작위 샘플링
      vs 시계열                         -> 구간설정

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_trian, y_val = train_test_split(
    X_combined, y, test_size = 0.2, random_stat = 42        # random_stat 는 실험 재현성
)

X_trian.shape, X_val.shape, y_train.shape, y_val.shape      # y_train = target (종속변수)

NameError: name 'X_combined' is not defined

# 모델링

In [25]:
from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=42)                   # 필수
dt_model.fit(X_train, y_train)                                      # 모델학습 끝

NameError: name 'X_train' is not defined

- (모델 학습 후)
- 다른 알고리즘 적용
  + 다중회귀 (통계적관점 -> 통계알고리즘)
  + 결정트리 
  + 경사하강법 (GBM)
  + 결정트리 + 경사하강법 (LightGBM, XGBoost, CatBoost)
  + Deep Learning